### ISSUE TITLE
Forgot Password feature

### ISSUE THREAD

**Issue by KnowledgeGarden** [topicquests/tqks-featherweight-prototype#20]
Needed to complete the authentication process

**Comment by KnowledgeGarden** [comment]
This is now in progress by Byron. It is adding an Email service which can be used for:

- Registration validation

- Forgot password

- Reset password

- Eventually, for activity notifications

**Comment by MonkeyBizNuss** [comment]
@qmeupscotty assigning to you, if you can please QA this one.

**Comment by qmeupscotty** [comment]
**Steps:**

1. Fill out email field
2. Click "Forgot Password"
3. Check for email and click the provided link
4. Fill out the fields and submit the new password

**Expected Result:**

User should be able to receive an email, click the link, be taken directly to password reset page, fill out the form, and reset their password

**Actual Result:**

As a user, I received the email and was able to click the link, but the link did not lead to anywhere due to an extra "/" in the URL. After removing the extra / from the address bar, I was able to get to the password reset page, but there was no option to submit my changes. I tried hitting "enter", but that didn't submit it either. I tried from an incognito window and the same thing occurred. 

<img width="1430" alt="screen shot 2019-02-26 at 10 59 16 am" src="https://user-images.githubusercontent.com/47651700/53439628-4b802b00-39b7-11e9-8c22-8aa67ef8fef9.png">

**Comment by MonkeyBizNuss** [comment]
@yepistemic @byroncoughlinSr can you please look into the actual results?

**Comment by byroncoughlinSr** [comment]
I will look into testing and fixing if necessary.

**Comment by byroncoughlinSr** [comment]
Is this in master or another repository?

**Comment by elog08** [comment]
@qmeupscotty , can you QA this?

**Comment by qmeupscotty** [comment]
**Steps:**

1. Fill out email field
2. Click "Forgot Password"
3. Check for email and click the provided link
4. Fill out the fields and submit the new password

**Expected Result:**

User should be able to receive an email, click the link, be taken directly to password reset page, fill out the form, reset their password, then sign in.

**Actual Result:**

As a user, I received the email and was able to click the link, but the link still did not lead to anywhere due to an extra "/" in the URL. After removing the extra / from the address bar, I was able to get to the password reset page and submit my change by clicking "Reset Password". Message reading "Password reset successful!, redirtecting to login" appeared, and I was redirected to the sign in page.

<img width="1018" alt="Screen Shot 2019-03-13 at 12 18 02 PM" src="https://user-images.githubusercontent.com/47651700/54309024-8f188e80-458c-11e9-9786-4a856152c905.png">

<img width="456" alt="Screen Shot 2019-03-13 at 12 24 02 PM" src="https://user-images.githubusercontent.com/47651700/54308828-0ef22900-458c-11e9-8460-a98ca1d929ed.png">

I attempted to sign in with the new password, but received an error saying "Cannot sign in, please check your email or password". 
I tried 3 more times to reset my password with no change in results. Although, I did notice that the error message appeared green once instead of red.

<img width="507" alt="Screen Shot 2019-03-13 at 12 19 23 PM" src="https://user-images.githubusercontent.com/47651700/54308802-fd108600-458b-11e9-9bd1-96b068efe66c.png">

<img width="462" alt="Screen Shot 2019-03-13 at 12 24 15 PM" src="https://user-images.githubusercontent.com/47651700/54308803-fd108600-458b-11e9-9f71-a8ad02a80dbe.png">

Ultimately, I was locked out of my account.

**Comment by byroncoughlinSr** [comment]
What branch is this being tested from?

**Comment by qmeupscotty** [comment]
@byroncoughlinSr 
Master
