### ISSUE TITLE
In mongodb arrays for questions, answers, pros, in the parent node etc are not populating correctly 

### ISSUE THREAD

**Issue by byroncoughlinSr** [topicquests/tqks-featherweight-prototype#93]
**Describe the bug**
In mongodb arrays for questions, answers, pros, in the parent node etc are not populating correctly 

**To Reproduce**
1. Create two questions, answers, pros, etc from nodeform
2. In mongodb shell typing db.conversations.find({})
3. looking at first node you will notice that the entire child object exist and only the nodeId of the second child exist

**Expected behavior**
Only the nodeId's should be listed in the arrays

**Comment by KnowledgeGarden** [comment]
This is all controlled by /src/api/src/services/conversations/conversation.hooks.js which is a Promise-based algorithm which ripples along defined child node arrays, each a list of nodeId values, then substituting into those arrays the fetched nodes, where the fetch of child nodes does not try to populate their child nodes. We really only need a nodes small image, its nodeId, and its label.

That process seems to work well for the first child node, but the second child node in an array will appear at the UI, but it is empty, because its nodeId still remains in the array; a crash occurs in the process of fetching that child, or somewhere in that process.

This is a process of substituting an array of fetched nodes for an array of their nodeId values, and not sending that back to the database, only to the UI.

**Comment by KnowledgeGarden** [comment]
I actually believe this can be closed. That's because the latest PR and merge gave me a master which is working just fine. I'm going to close it.
